#!/bin/bash

ARGTYPE="$1"
ENVNAME="$2"

case $ARGTYPE in

    create)
        (cd ~/Documents/environments; virtualenv $ENVNAME)
        ;;
    
    activate)
        source ~/Documents/environments/$ENVNAME/bin/activate
        ;;

    delete)
        (cd ~/Documents/environments; rm -r $ENVNAME)
        ;;

esac
